// This file is automatically generated by KvsStructConverter.exe.

using System;
using System.Runtime.InteropServices;

namespace CommonObj 
{ 
	class KvStruct {
		const int FlowControl_WSIZE = 100;
		const int Motion_Control_WSIZE = 100;
		const int Motion_Parameter_WSIZE = 100;
		const int Motion_Status_WSIZE = 100;
		const int Motion_UnitControl_WSIZE = 100;


		public class FlowControl {
			 public bool AutoRun = default(bool);
			 public bool OneStepEnable = default(bool);
			 public bool OneStepCountrol = default(bool);
			 public bool Reset = default(bool);
			 public bool Pause = default(bool);
			 public bool ErrorTimeEnable = default(bool);
			 public bool DelayTimeEnable = default(bool);
			 public bool OutErrorTime = default(bool);
			 public ushort SetErrorTime = default(ushort);
			 public ushort CountErrorTime = default(ushort);
			 public ushort SetDelayTime = default(ushort);
			 public ushort CountDelayTime = default(ushort);
			 public ushort AutoStep = default(ushort);
		}

		public class Motion_Control {
			 public bool ServerON = default(bool);
			 public bool JogPostive = default(bool);
			 public bool JogNegative = default(bool);
			 public bool JogHighSpeed = default(bool);
			 public bool OriginStr = default(bool);
			 public bool PositionStr = default(bool);
			 public ushort PointNum = default(ushort);
			 public bool ClearError = default(bool);
			 public bool DecelerationStop = default(bool);
		}

		public class Motion_Parameter {
			 public ushort TESTE = default(ushort);
		}

		public class Motion_Status {
			 public bool OriginFin = default(bool);
			 public bool OriginErr = default(bool);
			 public ushort AxisNum = default(ushort);
		}

		public class Motion_UnitControl {
			 public bool Enable = default(bool);
			 public ushort UnitNo = default(ushort);
		}

		public static int[] NewIndices(Array target) {
			int rank = target.Rank;
			int[] indices = new int[rank];
			Array.Clear(indices, 0, rank);
			indices[rank - 1]--;
			return indices;
		}

		public static void NextIndices(Array target, int[] indices) {
			int rank = target.Rank;
			indices[rank - 1]++;
			for (int dim = rank - 1; dim >= 0; dim--) {
				if (indices[dim] > target.GetUpperBound(dim)) {
					if (dim == 0) break;
					for (int j = dim; j < rank; j++) indices[j] = target.GetLowerBound(j);
					indices[dim - 1]++;
				}
			}
		}

		public static Array CreateClassInstanceArray<T>(int[] sizes) {
			Array entity = Array.CreateInstance(typeof(T), sizes);
			int[] indices = NewIndices(entity);
			for (int i = 0; i < entity.Length; i++) {
				NextIndices(entity, indices);
				entity.SetValue(Activator.CreateInstance(typeof(T)), indices);
			}
			return entity;
		}

		private static void SwapBytes(byte[] tgt, int byteSize, int byteOffset = 0) {
			byte tmpByte;
			for (int i = 0; i < byteSize / 2; i++) {
				tmpByte = tgt[i * 2 + byteOffset];
				tgt[i * 2] = tgt[i * 2 + 1 + byteOffset];
				tgt[i * 2 + 1 + byteOffset] = tmpByte;
			}
		}

		public static void ByteToBoolBase(Array dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
				int byteOffset = (wordOffset * 2) + (bitOffset / 8);
				int byteBitOffset = bitOffset % 8;
				int[] indices = NewIndices(src);
				for (int i = 0; i < len; i++) {
					NextIndices(src, indices);
					dst.SetValue((src[((i + byteBitOffset) / 8) + byteOffset] & (1 << (i + byteBitOffset) % 8)) != 0, indices);
				}
		}

		public static void ByteToBool(ref bool dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			int byteOffset = (wordOffset * 2) + (bitOffset / 8);
			int byteBitOffset = bitOffset % 8;
			dst = (src[byteOffset] & 1 << byteBitOffset) != 0;
		}

		public static void ByteToBool(ref bool[] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}
		public static void ByteToBool(ref bool[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			ByteToBoolBase(dst, src, len, wordOffset, bitOffset);
		}

		public static void ByteToShort(ref short dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToInt16(src, wordOffset * 2);
		}

		public static void ByteToShort(ref short[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}
		public static void ByteToShort(ref short[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(short));
		}

		public static void ByteToUshort(ref ushort dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToUInt16(src, wordOffset * 2);
		}

		public static void ByteToUshort(ref ushort[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}
		public static void ByteToUshort(ref ushort[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(ushort));
		}

		public static void ByteToInt(ref int dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToInt32(src, wordOffset * 2);
		}

		public static void ByteToInt(ref int[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}
		public static void ByteToInt(ref int[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(int));
		}

		public static void ByteToUint(ref uint dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToUInt32(src, wordOffset * 2);
		}

		public static void ByteToUint(ref uint[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}
		public static void ByteToUint(ref uint[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(uint));
		}

		public static void ByteToFloat(ref float dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToSingle(src, wordOffset * 2);
		}

		public static void ByteToFloat(ref float[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}
		public static void ByteToFloat(ref float[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(float));
		}

		public static void ByteToDouble(ref double dst, byte[] src, int len = 1, int wordOffset = 0) {
			dst = BitConverter.ToDouble(src, wordOffset * 2);
		}

		public static void ByteToDouble(ref double[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}
		public static void ByteToDouble(ref double[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, wordOffset * 2, dst, 0, len * sizeof(double));
		}

		public static void ByteToString(ref byte[] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}
		public static void ByteToString(ref byte[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			byte[] strTmp = new byte[len * stringSize];
			Array.Copy(src, wordOffset * 2, strTmp, 0, len * stringSize);
			SwapBytes(strTmp, len * stringSize);
			Buffer.BlockCopy(strTmp, 0, dst, 0, len * stringSize);
		}

		public static void BoolToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			int[] indices = NewIndices(dst);
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				BoolToByte(ref dst, (bool)src.GetValue(indices), 1, wordOffset, bitOffset);
				bitOffset++;
				if (bitOffset >= 16) {
					bitOffset = 0;
					wordOffset++;
				}
			}
		}

		public static void BoolToByte(ref byte[] dst, bool src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			int byteOffset = (wordOffset * 2) + (bitOffset / 8);
			int byteBitOffset = bitOffset % 8;
			if (src) {
				dst[byteOffset] |= (byte)(1 << byteBitOffset);
			}
			else {
				dst[byteOffset] &= (byte)~(1 << byteBitOffset);
			}
		}

		public static void BoolToByte(ref byte[] dst, bool[] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,,,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,,,,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}
		public static void BoolToByte(ref byte[] dst, bool[,,,,,,,] src, int len = 1, int wordOffset = 0, int bitOffset = 0) {
			BoolToByteBase(ref dst, src, len, wordOffset, bitOffset);
		}

		public static void ShortToByte(ref byte[] dst, short src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(short));
		}

		public static void ShortToByte(ref byte[] dst, short[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}
		public static void ShortToByte(ref byte[] dst, short[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(short));
		}

		public static void UshortToByte(ref byte[] dst, ushort src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(ushort));
		}

		public static void UshortToByte(ref byte[] dst, ushort[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}
		public static void UshortToByte(ref byte[] dst, ushort[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(ushort));
		}

		public static void IntToByte(ref byte[] dst, int src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(int));
		}

		public static void IntToByte(ref byte[] dst, int[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}
		public static void IntToByte(ref byte[] dst, int[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(int));
		}

		public static void UintToByte(ref byte[] dst, uint src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(uint));
		}

		public static void UintToByte(ref byte[] dst, uint[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}
		public static void UintToByte(ref byte[] dst, uint[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(uint));
		}

		public static void FloatToByte(ref byte[] dst, float src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(float));
		}

		public static void FloatToByte(ref byte[] dst, float[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}
		public static void FloatToByte(ref byte[] dst, float[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(float));
		}

		public static void DoubleToByte(ref byte[] dst, double src, int len = 1, int wordOffset = 0) {
			Array.Copy(BitConverter.GetBytes(src), 0, dst, wordOffset * 2, len * sizeof(double));
		}

		public static void DoubleToByte(ref byte[] dst, double[] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}
		public static void DoubleToByte(ref byte[] dst, double[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * sizeof(double));
		}

		public static void StringToByte(ref byte[] dst, byte[] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,,,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,,,,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}
		public static void StringToByte(ref byte[] dst, byte[,,,,,,,] src, int len = 1, int wordOffset = 0, int stringSize = 0) {
			Buffer.BlockCopy(src, 0, dst, wordOffset * 2, len * stringSize);
			SwapBytes(dst, len * stringSize, wordOffset * 2);
		}

		public static void ByteTo_FlowControl(ref FlowControl dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBool(ref dst.AutoRun, src, 1, 0 + wordOffset, 0);
			ByteToBool(ref dst.OneStepEnable, src, 1, 0 + wordOffset, 1);
			ByteToBool(ref dst.OneStepCountrol, src, 1, 0 + wordOffset, 2);
			ByteToBool(ref dst.Reset, src, 1, 0 + wordOffset, 3);
			ByteToBool(ref dst.Pause, src, 1, 0 + wordOffset, 4);
			ByteToBool(ref dst.ErrorTimeEnable, src, 1, 0 + wordOffset, 5);
			ByteToBool(ref dst.DelayTimeEnable, src, 1, 0 + wordOffset, 6);
			ByteToBool(ref dst.OutErrorTime, src, 1, 0 + wordOffset, 7);
			ByteToUshort(ref dst.SetErrorTime, src, 1, 1 + wordOffset);
			ByteToUshort(ref dst.CountErrorTime, src, 1, 2 + wordOffset);
			ByteToUshort(ref dst.SetDelayTime, src, 1, 3 + wordOffset);
			ByteToUshort(ref dst.CountDelayTime, src, 1, 4 + wordOffset);
			ByteToUshort(ref dst.AutoStep, src, 1, 5 + wordOffset);
		}
		private static void ByteToBase_FlowControl(Array dst, byte[] src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(dst);
			FlowControl elemTmp = new FlowControl();
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				ByteTo_FlowControl(ref elemTmp, src, len, wordOffset);
				dst.SetValue(elemTmp, indices);
				wordOffset += FlowControl_WSIZE;
			}
		}
		public static void ByteTo_FlowControl(ref FlowControl[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_FlowControl(ref FlowControl[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_FlowControl(dst, src, len, wordOffset);
		}

		public static void ByteTo_Motion_Control(ref Motion_Control dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBool(ref dst.ServerON, src, 1, 0 + wordOffset, 0);
			ByteToBool(ref dst.JogPostive, src, 1, 0 + wordOffset, 1);
			ByteToBool(ref dst.JogNegative, src, 1, 0 + wordOffset, 2);
			ByteToBool(ref dst.JogHighSpeed, src, 1, 0 + wordOffset, 3);
			ByteToBool(ref dst.OriginStr, src, 1, 0 + wordOffset, 4);
			ByteToBool(ref dst.PositionStr, src, 1, 0 + wordOffset, 5);
			ByteToUshort(ref dst.PointNum, src, 1, 1 + wordOffset);
			ByteToBool(ref dst.ClearError, src, 1, 2 + wordOffset, 0);
			ByteToBool(ref dst.DecelerationStop, src, 1, 2 + wordOffset, 1);
		}
		private static void ByteToBase_Motion_Control(Array dst, byte[] src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(dst);
			Motion_Control elemTmp = new Motion_Control();
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				ByteTo_Motion_Control(ref elemTmp, src, len, wordOffset);
				dst.SetValue(elemTmp, indices);
				wordOffset += Motion_Control_WSIZE;
			}
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Control(ref Motion_Control[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Control(dst, src, len, wordOffset);
		}

		public static void ByteTo_Motion_Parameter(ref Motion_Parameter dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToUshort(ref dst.TESTE, src, 1, 0 + wordOffset);
		}
		private static void ByteToBase_Motion_Parameter(Array dst, byte[] src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(dst);
			Motion_Parameter elemTmp = new Motion_Parameter();
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				ByteTo_Motion_Parameter(ref elemTmp, src, len, wordOffset);
				dst.SetValue(elemTmp, indices);
				wordOffset += Motion_Parameter_WSIZE;
			}
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Parameter(ref Motion_Parameter[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Parameter(dst, src, len, wordOffset);
		}

		public static void ByteTo_Motion_Status(ref Motion_Status dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBool(ref dst.OriginFin, src, 1, 0 + wordOffset, 0);
			ByteToBool(ref dst.OriginErr, src, 1, 0 + wordOffset, 1);
			ByteToUshort(ref dst.AxisNum, src, 1, 1 + wordOffset);
		}
		private static void ByteToBase_Motion_Status(Array dst, byte[] src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(dst);
			Motion_Status elemTmp = new Motion_Status();
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				ByteTo_Motion_Status(ref elemTmp, src, len, wordOffset);
				dst.SetValue(elemTmp, indices);
				wordOffset += Motion_Status_WSIZE;
			}
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_Status(ref Motion_Status[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_Status(dst, src, len, wordOffset);
		}

		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBool(ref dst.Enable, src, 1, 0 + wordOffset, 0);
			ByteToUshort(ref dst.UnitNo, src, 1, 1 + wordOffset);
		}
		private static void ByteToBase_Motion_UnitControl(Array dst, byte[] src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(dst);
			Motion_UnitControl elemTmp = new Motion_UnitControl();
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(dst, indices);
				ByteTo_Motion_UnitControl(ref elemTmp, src, len, wordOffset);
				dst.SetValue(elemTmp, indices);
				wordOffset += Motion_UnitControl_WSIZE;
			}
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}
		public static void ByteTo_Motion_UnitControl(ref Motion_UnitControl[,,,,,,,] dst, byte[] src, int len = 1, int wordOffset = 0) {
			ByteToBase_Motion_UnitControl(dst, src, len, wordOffset);
		}

		public static void FlowControl_ToByte(ref byte[] dst, FlowControl src, int len = 1, int wordOffset = 0) {
			BoolToByte(ref dst, src.AutoRun, 1, 0 + wordOffset, 0);
			BoolToByte(ref dst, src.OneStepEnable, 1, 0 + wordOffset, 1);
			BoolToByte(ref dst, src.OneStepCountrol, 1, 0 + wordOffset, 2);
			BoolToByte(ref dst, src.Reset, 1, 0 + wordOffset, 3);
			BoolToByte(ref dst, src.Pause, 1, 0 + wordOffset, 4);
			BoolToByte(ref dst, src.ErrorTimeEnable, 1, 0 + wordOffset, 5);
			BoolToByte(ref dst, src.DelayTimeEnable, 1, 0 + wordOffset, 6);
			BoolToByte(ref dst, src.OutErrorTime, 1, 0 + wordOffset, 7);
			UshortToByte(ref dst, src.SetErrorTime, 1, 1 + wordOffset);
			UshortToByte(ref dst, src.CountErrorTime, 1, 2 + wordOffset);
			UshortToByte(ref dst, src.SetDelayTime, 1, 3 + wordOffset);
			UshortToByte(ref dst, src.CountDelayTime, 1, 4 + wordOffset);
			UshortToByte(ref dst, src.AutoStep, 1, 5 + wordOffset);
		}
		private static void FlowControl_ToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(src);
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(src, indices);
				FlowControl_ToByte(ref dst, (FlowControl)src.GetValue(indices), len, wordOffset);
				wordOffset += FlowControl_WSIZE;
			}
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,,,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,,,,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void FlowControl_ToByte(ref byte[] dst, FlowControl[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			FlowControl_ToByteBase(ref dst, src, len, wordOffset);
		}

		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control src, int len = 1, int wordOffset = 0) {
			BoolToByte(ref dst, src.ServerON, 1, 0 + wordOffset, 0);
			BoolToByte(ref dst, src.JogPostive, 1, 0 + wordOffset, 1);
			BoolToByte(ref dst, src.JogNegative, 1, 0 + wordOffset, 2);
			BoolToByte(ref dst, src.JogHighSpeed, 1, 0 + wordOffset, 3);
			BoolToByte(ref dst, src.OriginStr, 1, 0 + wordOffset, 4);
			BoolToByte(ref dst, src.PositionStr, 1, 0 + wordOffset, 5);
			UshortToByte(ref dst, src.PointNum, 1, 1 + wordOffset);
			BoolToByte(ref dst, src.ClearError, 1, 2 + wordOffset, 0);
			BoolToByte(ref dst, src.DecelerationStop, 1, 2 + wordOffset, 1);
		}
		private static void Motion_Control_ToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(src);
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(src, indices);
				Motion_Control_ToByte(ref dst, (Motion_Control)src.GetValue(indices), len, wordOffset);
				wordOffset += Motion_Control_WSIZE;
			}
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Control_ToByte(ref byte[] dst, Motion_Control[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Control_ToByteBase(ref dst, src, len, wordOffset);
		}

		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter src, int len = 1, int wordOffset = 0) {
			UshortToByte(ref dst, src.TESTE, 1, 0 + wordOffset);
		}
		private static void Motion_Parameter_ToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(src);
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(src, indices);
				Motion_Parameter_ToByte(ref dst, (Motion_Parameter)src.GetValue(indices), len, wordOffset);
				wordOffset += Motion_Parameter_WSIZE;
			}
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Parameter_ToByte(ref byte[] dst, Motion_Parameter[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Parameter_ToByteBase(ref dst, src, len, wordOffset);
		}

		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status src, int len = 1, int wordOffset = 0) {
			BoolToByte(ref dst, src.OriginFin, 1, 0 + wordOffset, 0);
			BoolToByte(ref dst, src.OriginErr, 1, 0 + wordOffset, 1);
			UshortToByte(ref dst, src.AxisNum, 1, 1 + wordOffset);
		}
		private static void Motion_Status_ToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(src);
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(src, indices);
				Motion_Status_ToByte(ref dst, (Motion_Status)src.GetValue(indices), len, wordOffset);
				wordOffset += Motion_Status_WSIZE;
			}
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_Status_ToByte(ref byte[] dst, Motion_Status[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_Status_ToByteBase(ref dst, src, len, wordOffset);
		}

		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl src, int len = 1, int wordOffset = 0) {
			BoolToByte(ref dst, src.Enable, 1, 0 + wordOffset, 0);
			UshortToByte(ref dst, src.UnitNo, 1, 1 + wordOffset);
		}
		private static void Motion_UnitControl_ToByteBase(ref byte[] dst, Array src, int len = 1, int wordOffset = 0) {
			int[] indices = NewIndices(src);
			int offset = wordOffset;
			for (int i = 0; i < len; i++) {
				NextIndices(src, indices);
				Motion_UnitControl_ToByte(ref dst, (Motion_UnitControl)src.GetValue(indices), len, wordOffset);
				wordOffset += Motion_UnitControl_WSIZE;
			}
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}
		public static void Motion_UnitControl_ToByte(ref byte[] dst, Motion_UnitControl[,,,,,,,] src, int len = 1, int wordOffset = 0) {
			Motion_UnitControl_ToByteBase(ref dst, src, len, wordOffset);
		}

	}
}
